### ISSUE TITLE
FSL BedpostX error

### ISSUE THREAD

**Issue by monicatly** [bircibrain/containers#14]
Running BedpostX draws the following error in the dmri.bedpostX log:
/usr/local/fsl/bin/bedpostx_preproc.sh: 71: /usr/local/fsl/bin/bedpostx_preproc.sh: /usr/local/fsl/bin/imcp: not found

**Comment by rhancockn** [comment]
Some part of the FSL installer is failing during the build such that some of the im* scripts don’t end up in FSL/bin. Check installer and error handlers.
